import { Montserrat } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "CGM Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
